### ISSUE TITLE
Make tournament matches live

### ISSUE THREAD

**Issue by Dr-Horv** [cygni/paintbot-webapp#36]
Events should already be sent, should just listen to them and do proper rendering of games lives rather then play and then show.

**Comment by 89netraM** [comment]
Hello! I'm excited about the next Paintbot tournament and I've looked a bit at this. However, I can't find where the events for this should be sent from. The only way I've found on how to receive `MapUpdateEvent` is to be a registered player. Have I missed something? Or could a `registerSpectator` request be added to the Tournament API?
